### PR TITLE
Update include.json

### PR DESCRIPTION
**Pull request by Boom-X2**
Add current repository for SuperDateTime to include.json file.

### CODE REVIEW

**Review by michaelherger — APPROVED** [review]
LGTM

**Comment by michaelherger** [comment]
Oh, actually we already have your repository file in there. There's no need to add anything. I'm going to revert this PR.

**Comment by Boom-X2** [comment]
I see @tcutting's repository in the include.json file which is for a variant of Erland's Custom Clock applet.
http://superdatetimewu.sourceforge.net/CC_JL_repo.xml

I do not see the SuperDateTime repository 
https://sdt-weather-com.sourceforge.net/repo.xml

Will it need to be in the include.json file for it to be picked up by your automated repository updates?

**Comment by michaelherger** [comment]
See https://github.com/LMS-Community/lms-plugin-repository/blob/5db9fdbe4b55c2c25f70f2812567868cfa1153b1/include.json#L27 ?

**Comment by Boom-X2** [comment]
Thanks Michael.  I looked right past that entry.  I saw netcologne and didn't further or realize it is a SourceForge mirror.

**Pull request merged**
